### ISSUE TITLE
Data types for Cube state

### ISSUE THREAD

**Issue by jradtilbrook** [jradtilbrook/rubiks#3]
The Cube state can be modelled with either 6 3x3 arrays (known as facelet model) directly representing each face of the cube, but a more succinct and likely faster/easier to code model is the 2x12 and 2x8 vectors (known as cubie model).

At first glance, I'd prefer to use the cubie model. Either way, since they are such simple data types (arrays), they may not benefit from defining a new strict type but should be investigated. Potentially both will be needed for human input vs. algorithm model.

**Comment by jradtilbrook** [comment]
@SaxJ I was thinking something along the lines of this (there might be errors in this snippet but hopefully you get the message)
```haskell
data EdgeOrientation = Incorrect | Correct deriving (Show, Read, Eq, Ord, Enum, Bounded)
data CornerOrientation = Clockwise | AntiClockwise | Correct deriving (Show, Read, Eq, Ord, Enum, Bounded)
data CornerOrientationVector = CornerOrientationVector CornerOrientation CornerOrientation CornerOrientation CornerOrientation CornerOrientation CornerOrientation CornerOrientation CornerOrientation deriving (Show, Read, Eq, Ord, Enum, Bounded)
```

The problem I've run into is that the `Correct` keyword is defined multiple times so I assume can't be used and must be named uniquely between types?
The names are also very verbose so it would be ideal to find good alternatives that are shorter anyway.  
What do you think?

**Comment by SaxJ** [comment]
I agree with going for the cubie model first. The operations on it are more straightforward.

In the example of the `Bool` type, True and False are called "value constructors" that produce a Bool type. So False is like a function that takes no arguments and produces a Bool. If you made a type `data Thing = Foo | Bar | False`, then you're basically defining another function False that produces a Thing type, so now the type system can't figure out what False is meant to produce.

`data EdgeOrientation = Incorrect | Correct
data CornerOrientation = Clock | AntiClock | Solved` maybe?

For CornerOrientationVector, maybe `type CornerOrientationVector = [CornerOrientation]`. Downside is we would be enforcing size of the vector in types then. :(

**Comment by jradtilbrook** [comment]
This was done in #16
